- hosts: localhost
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes
  roles:
  - role: geerlingguy.nodejs
  - role: geerlingguy.docker
  - role: geerlingguy.pip
  - role: custom-setup
  - role: gantsign.visual-studio-code
    users:
      - username: lennart
  - role: lean_delivery.java
    java_major_version: 11
    java_tarball_install: true
    transport: web
    transport_web: https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
  - role: gantsign.maven
  - role: gantsign.intellij
    intellij_default_maven_home: '/opt/maven/apache-maven-3.3.9'
    users:
      - username: lennart
        intellij_jdks:
          - name: '1.11'
            home: '/usr/lib/jvm/jdk-11.0.2'
          - name: '1.8'
            home: '/usr/lib/jvm/java-8-openjdk-amd64'
        intellij_default_jdk: '1.11'
        intellij_disabled_plugins:
          - org.jetbrains.plugins.gradle
          - CVS
          - com.intellij.uiDesigner
          - org.jetbrains.android
          - TestNG-J
          - hg4idea
          - Subversion
          - AntSupport
          - DevKit
        intellij_codestyles:
          - name: GoogleStyle
            url: 'https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml'
        intellij_default_codestyle: GoogleStyle
        intellij_inspection_profiles:
          - name: GantSign
            url: 'https://raw.githubusercontent.com/gantsign/inspection-profile-intellij/master/GantSign.xml'
        intellij_default_inspection_profile: GantSign
        intellij_plugins:
          - CheckStyle-IDEA
